import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";
@Entity() // the entity decorator asks nest to create a database table mpde;
export class User {
    @PrimaryGeneratedColumn() // lets us create a primary key which is going to be autogenerated
    id: number;

    @Column() // asks nest to create a column 
    firstName: string;

    @Column({nullable: true})
    middleName: string;

    @Column()
    lastName: string;

    @Column()
    email: string;

    @Column({nullable: true}) 
    dateOfBirth: Date; 

    @Column({nullable: true}) 
    nationality: string 

    @Column({nullable: true}) 
    address: string 

    @Column({ default: true }) 
    isActive: boolean; 
}
